### ISSUE TITLE
[BUG] Circular hitboxes are broken

### ISSUE THREAD

**Issue by Beyley** [Eeveelution/Furball#4]
**Describe the bug**
When you set a drawable to be circular its hitbox is all sorts of broken

**To Reproduce**
1. Create a drawable, set it to be circular, then test its hitbox

**Expected behavior**
The hitbox should be perfectly circular

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [aff71755c7436ded87c9a0d7d360e46d49e5cf66]

**Comment by Eeveelution** [comment]
must have been broken by the new change in primitive drawing libraries

**Comment by Beyley** [comment]
> must have been broken by the new change in primitive drawing libraries

Possibly, ill go ahead and rewrite the circular hitbox algorithm with some real documentation this time

**Comment by Beyley** [comment]
Closed in 38cb0667dd448fa6263b477a5e85c8e39f166430
